language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false
dist: trusty

install:
  - travis_retry composer update --no-interaction --prefer-dist

matrix:
  allow_failures:
    - php: 5.4

script: vendor/bin/phpunit
